-- =====================================================
-- SPEC 11: Bulletproof Server-Side State System
-- Migration 008: Clean slate implementation
-- =====================================================

-- =====================================================
-- USER CURRENCY TABLE
-- Single source of truth for all currency balances
-- =====================================================
CREATE TABLE IF NOT EXISTS user_currency (
  user_id TEXT PRIMARY KEY,

  -- Current balances
  oranges INTEGER NOT NULL DEFAULT 100,  -- Starting balance
  gems INTEGER NOT NULL DEFAULT 0,

  -- Lifetime totals (for achievements, never decreases)
  lifetime_oranges INTEGER NOT NULL DEFAULT 100,
  lifetime_gems INTEGER NOT NULL DEFAULT 0,

  -- Gifted oranges (tracked separately, cannot convert to crypto)
  gifted_oranges INTEGER NOT NULL DEFAULT 0,

  -- Compliance-ready fields (for future KYC)
  verification_status TEXT DEFAULT 'none',  -- 'none', 'pending', 'verified', 'rejected'
  verification_date TEXT,
  withdrawal_enabled INTEGER DEFAULT 0,
  total_withdrawn INTEGER DEFAULT 0,

  -- Timestamps
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- =====================================================
-- USER ACHIEVEMENTS TABLE
-- Tracks progress and claim status for each achievement
-- =====================================================
CREATE TABLE IF NOT EXISTS user_achievements (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  achievement_id TEXT NOT NULL,

  -- Progress tracking
  progress INTEGER NOT NULL DEFAULT 0,
  target INTEGER NOT NULL,

  -- Completion status
  completed_at TEXT,  -- NULL if not completed

  -- Claim status (completed != claimed)
  claimed_at TEXT,    -- NULL if not claimed
  reward_oranges INTEGER,  -- Reward given on claim
  reward_gems INTEGER,

  -- Timestamps
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,

  UNIQUE(user_id, achievement_id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_user_achievements_user ON user_achievements(user_id);
CREATE INDEX IF NOT EXISTS idx_user_achievements_unclaimed ON user_achievements(user_id, completed_at, claimed_at);

-- =====================================================
-- USER STATS TABLE
-- Aggregated stats for achievement checking
-- =====================================================
CREATE TABLE IF NOT EXISTS user_stats (
  user_id TEXT PRIMARY KEY,

  -- Gameplay stats
  total_games_played INTEGER NOT NULL DEFAULT 0,
  highest_score INTEGER NOT NULL DEFAULT 0,
  highest_score_game TEXT,
  games_played_by_id TEXT DEFAULT '{}',  -- JSON: { "game-id": count }

  -- Social stats
  friends_count INTEGER NOT NULL DEFAULT 0,

  -- Collection stats
  items_owned INTEGER NOT NULL DEFAULT 0,

  -- Profile completion
  has_custom_name INTEGER NOT NULL DEFAULT 0,
  has_custom_avatar INTEGER NOT NULL DEFAULT 0,
  has_nft_avatar INTEGER NOT NULL DEFAULT 0,

  -- Timestamps
  created_at TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- =====================================================
-- GAME SESSIONS TABLE
-- Prevents replay attacks and validates game completions
-- =====================================================
CREATE TABLE IF NOT EXISTS game_sessions (
  id TEXT PRIMARY KEY,  -- UUID generated by client
  user_id TEXT NOT NULL,
  game_id TEXT NOT NULL,

  -- Session state
  started_at TEXT DEFAULT CURRENT_TIMESTAMP,
  completed_at TEXT,

  -- Game data (set on completion)
  final_score INTEGER,
  duration_seconds INTEGER,

  -- Reward tracking
  reward_claimed INTEGER NOT NULL DEFAULT 0,
  reward_amount INTEGER,

  -- Anti-cheat
  client_hash TEXT,  -- Hash of game state for validation

  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_game_sessions_user ON game_sessions(user_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_game_sessions_unclaimed ON game_sessions(user_id, reward_claimed, completed_at);

-- =====================================================
-- DAILY LOGIN CLAIMS TABLE
-- Prevents double-claiming daily rewards
-- =====================================================
CREATE TABLE IF NOT EXISTS daily_login_claims (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  claim_date TEXT NOT NULL,  -- YYYY-MM-DD format
  streak_day INTEGER NOT NULL,  -- 1-7
  oranges_claimed INTEGER NOT NULL,
  gems_claimed INTEGER NOT NULL DEFAULT 0,

  created_at TEXT DEFAULT CURRENT_TIMESTAMP,

  UNIQUE(user_id, claim_date),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_daily_login_claims_user ON daily_login_claims(user_id, claim_date DESC);

-- =====================================================
-- DAILY CHALLENGE PROGRESS TABLE
-- =====================================================
CREATE TABLE IF NOT EXISTS daily_challenge_progress (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  challenge_date TEXT NOT NULL,  -- YYYY-MM-DD (UTC)
  challenge_id TEXT NOT NULL,    -- 'games-played-5', 'personal-best-1', 'play-time-600'

  -- Progress
  progress INTEGER NOT NULL DEFAULT 0,
  target INTEGER NOT NULL,

  -- Completion & claim
  completed_at TEXT,
  claimed_at TEXT,
  reward_amount INTEGER,

  UNIQUE(user_id, challenge_date, challenge_id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_daily_challenge_progress_user ON daily_challenge_progress(user_id, challenge_date);

-- =====================================================
-- ACTIVE SESSIONS TABLE
-- Single-session enforcement (one active game per user)
-- =====================================================
CREATE TABLE IF NOT EXISTS active_sessions (
  user_id TEXT PRIMARY KEY,
  game_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  started_at TEXT DEFAULT CURRENT_TIMESTAMP,
  last_heartbeat TEXT DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- =====================================================
-- FLAGGED SCORES TABLE
-- Statistical anomaly detection for review
-- =====================================================
CREATE TABLE IF NOT EXISTS flagged_scores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,
  game_id TEXT NOT NULL,
  session_id TEXT NOT NULL,
  score INTEGER NOT NULL,

  -- Why it was flagged
  flag_reason TEXT NOT NULL,  -- 'percentile_99', 'impossible_time', 'pattern_anomaly'
  flag_details TEXT,          -- JSON with specifics

  -- Review status
  reviewed_at TEXT,
  reviewed_by TEXT,
  verdict TEXT,  -- 'legitimate', 'cheating', 'uncertain'

  created_at TEXT DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_flagged_scores_user ON flagged_scores(user_id);
CREATE INDEX IF NOT EXISTS idx_flagged_scores_unreviewed ON flagged_scores(reviewed_at);

-- =====================================================
-- BANNED USERS TABLE
-- Zero tolerance cheater ban system
-- =====================================================
CREATE TABLE IF NOT EXISTS banned_users (
  user_id TEXT PRIMARY KEY,
  banned_at TEXT DEFAULT CURRENT_TIMESTAMP,
  reason TEXT NOT NULL,
  evidence TEXT,  -- JSON with proof

  -- For potential appeals
  appeal_status TEXT DEFAULT 'none',  -- 'none', 'pending', 'denied', 'approved'
  appeal_notes TEXT,

  FOREIGN KEY (user_id) REFERENCES users(id)
);

-- =====================================================
-- WITHDRAWAL REQUESTS TABLE
-- Compliance-ready for future KYC
-- =====================================================
CREATE TABLE IF NOT EXISTS withdrawal_requests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL,

  -- Amount
  oranges_amount INTEGER NOT NULL,
  hoa_amount REAL NOT NULL,  -- Calculated at request time

  -- Status
  status TEXT DEFAULT 'pending',  -- 'pending', 'processing', 'completed', 'rejected'
  status_reason TEXT,

  -- Blockchain details (filled on completion)
  transaction_hash TEXT,
  wallet_address TEXT,

  -- Timestamps
  requested_at TEXT DEFAULT CURRENT_TIMESTAMP,
  processed_at TEXT,

  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_user ON withdrawal_requests(user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawal_requests_status ON withdrawal_requests(status);
